version: '3'
services:
  # when deploying for production, we are using the images that our CI server pushed to Docker Hub
  client:
    image: 'rallycoding/multi-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'rallycoding/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - NODE_ENV=production
  worker:
    image: 'rallycoding/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - NODE_ENV=production
  nginx:
    image: 'rallycoding/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
