name: Deploy K8s to Google Cloud
# on:
#   push:
#     branches:
#       - main 

# only run when manually triggered
on: 
  workflow_dispatch:

# set the current commit as an env variable to be used throughout your steps
env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # login to docker so we can push to dockerhub, build our dev image and then execute out test script
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true rallycoding/react-test npm test

        # authenticate with Google Cloud services
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # set up Google Cloud SDK and configure it to use the project we setup
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-338920

      # - name: Auth
      #   run: |-
      #     gcloud --quiet auth configure-docker

      # get  credentials needed to interact with our Google Kubernetes Engine (GKE) cluster and set the context of our kubectl command to point to this cluster.
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      # build and tag each prod image with the current git commit id
      - name: Build
        run: |-
          docker build -t rallycoding/multi-client-k8s-gh:latest -t rallycoding/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t rallycoding/multi-server-k8s-gh:latest -t rallycoding/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t rallycoding/multi-worker-k8s-gh:latest -t rallycoding/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      # push each image to Dockerhub under 2 different tags: "latest" and the secific git commit id 
      - name: Push
        run: |-
          docker push rallycoding/multi-client-k8s-gh:latest
          docker push rallycoding/multi-server-k8s-gh:latest
          docker push rallycoding/multi-worker-k8s-gh:latest

          docker push rallycoding/multi-client-k8s-gh:${{ env.SHA }}
          docker push rallycoding/multi-server-k8s-gh:${{ env.SHA }}
          docker push rallycoding/multi-worker-k8s-gh:${{ env.SHA }}

      # (kubcetl will interact with the remote cluster)
      # 1. applies manifest files incase any changes were made to them in this commit
      # 2. then updates each deployment to use the new images pushed to Dockerhub 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=rallycoding/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=rallycoding/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=rallycoding/multi-worker-k8s-gh:${{ env.SHA }}
